### ISSUE TITLE
Server setup - digital ocean example

### ISSUE THREAD

**Issue by rarkins** [anderspitman/SirTunnel#10]
I'm hoping to run the server on a Digital Ocean droplet. Is the following a good plan?

- Create a new droplet (let's assume I use my SSH key instead of password-based)
- Create a dedicated sirtunnel user so I'm not running as root
- Create an SSH keypair `id_sirtunnel` for this new user. The private key is what will be used by users/clients
- Clone SirTunnel to the droplet, run the `install.sh` and then `run_server.sh`
- Register a dedicated domain for this (let's say `rarkinstunnel.com`)
- Configure a wildcard DNS entry for `rarkinstunnel.com` pointing to my droplet IP
- `ssh -i ~/.ssh/id_sirtunnel -tR 9001:localhost:8080 rarkinstunnel.com sirtunnel.py sub1.rarkinstunnel.com 9001`

Is that enough, including for Caddy to somehow fetch certs from LetsEncrypt for rarkinstunnel.com?

BTW I'm not sure I understand the 9001 port, which I've copied directly from your example. Does that need to be unique for each different user/tunnel I wish to run?

**Comment by anderspitman** [comment]
Hey @rarkins, I haven't used SirTunnel in a while (I use boringproxy, which you might consider taking a look at), but this sounds basically right. You'll probably need to do a bit of tweaking, and I'd recommend using a newer version of Caddy (by updating `install.sh`).

And yes 9001 is an arbitrary port for the example, and you'll need to use a different port for each tunnel.
