### ISSUE TITLE
Port 80 listening issue?

### ISSUE THREAD

**Issue by zefoo** [anderspitman/SirTunnel#13]
Hello! This seems pretty slick. I've had issues with serveo and localtunnel in the past. Hoping this will be "the answer." 

I can get things working with this `json` config:

```
{
  "apps": {
    "http": {
      "servers": {
        "sirtunnel": {
          "listen": [":4443"],
          "routes": [
          ]
        }
      }
    }
  }
}
```

I've got nginx running on this system and need to use a non-standard port. The issue I get now is when I try to connect to sir tunnel, it looks like caddy is throwing this error:

```
2023/08/13 21:56:38.564 ERROR   admin.api       request error   {"error": "loading new config: http app module: start: tcp: listening on :80: listen tcp :80: bind: address already in use", "status_code": 500}
```

I'm currently exploring caddy docs trying to figure this out. Thought I'd ask here in the event someone knew how to change this. I think this is the last piece of the puzzle.

**Comment by anderspitman** [comment]
Looks like you have another program (probably a webserver) using port 80. Maybe nginx or something? What do you see if you `curl localhost` on the machine?

**Comment by zefoo** [comment]
Thank you @anderspitman . I most certainly do. Can I change port 80 with sirtunnel/caddy to be something else? I can't seem to figure this out. Would love to run nginx on here too for other purposes.

**Comment by zefoo** [comment]
Ok, I got it. My json conf:

```
{
  "apps": {
    "http": {
      "http_port": 8844,
      "servers": {
        "sirtunnel": {
          "listen": [":4443"],
          "routes": [
          ]
        }
      }
    }
  }
}
```

Although the issue with this... is the SSL cert doesn't seem to respect port 8844. Is this needed for the SSL cert? 

Getting this:

```
2023/08/16 03:54:37 [ERROR] attempt 7: [user.local.domain.com] Obtain: [user.local.domain.com] error: one or more domains had a problem:
[user.local.domain.com] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: 167.71.123.91: Invalid response from http://user.local.domain.com/.well-known/acme-challenge/MPalbX4A-Zt3YnWBgVDTO1m-QUQXY6oLfo: 404, url:
 - retrying in 20m0s (41m30.941544586s/720h0m0s elapsed)...
```

**Comment by anderspitman** [comment]
I'm not sure what the best way to achieve this would be. Since you're already running nginx, can you just use that to set up tunnels manually? ie something like this:

https://jerrington.me/posts/2019-01-29-self-hosted-ngrok.html
