### ISSUE TITLE
"remote port forwarding failed"

### ISSUE THREAD

**Issue by zefoo** [anderspitman/SirTunnel#15]
If my connection doesn't clean up well/network issue, I sometimes get this error:

Warning: remote port forwarding failed for listen port 11369

I have to change the port or restart / kill process with SirTunnel. Is there a way to have SirTunnel force override the port so this issue can be avoided?

**Comment by anderspitman** [comment]
I only personally used SirTunnel for a brief time before creating boringproxy. As such it's a very basic tool. Maybe this fork has what you need?

https://github.com/anderspitman/SirTunnel/pull/12
