### ISSUE TITLE
sirtunnel.py: command not found

### ISSUE THREAD

**Issue by joseyapor21** [anderspitman/SirTunnel#4]
I have this error how can I get the path sirtunnel.py on the server?

**Comment by anderspitman** [comment]
Hi @joseyapor21, you'll need both sirtunnel.py and Caddy on the server. Easiest way is to log in to the server and do a git clone, then run the install script. SirTunnel is a bit more hands on. You'll need a decent understanding of SSH tunnels and reverse proxies (Caddy in particular). You might check this list for some more user-friendly options:

https://github.com/anderspitman/awesome-tunneling

**Comment by joseyapor21** [comment]
Thanks for the reply I was able to find the sirtunnel.py on the server and able to make a tunnel,
I have a question there is an API call made by sirtunnel.py where is this request going to and where are those files, I'm new to this Thanks in advance.
"method": "POST", "host": "127.0.0.1:2019", "uri": "/config/apps/http/servers/sirtunnel/routes", "remote_addr": "127.0.0.1:41404", "headers": {"Accept-Encoding":["identity"],"Connection":["close"],"Content-Length":["157"],"Content-Type":["application/json"],"User-Agent":["Python-urllib/3.5"]

**Comment by joseyapor21** [comment]
This is not an issue is more like user documentation I was able to figure out the sirtunnel.py and the API comes from 127.0.0.1:2019
that comes with CADDY is a way to send CADDY the information of the tunnels and add the routes thanks I just read about Caddy it is very helpful,
Thanks for this great app.

**Comment by anderspitman** [comment]
No problem glad you figured it out!
