### ISSUE TITLE
Where do I need to run SirTunnel server instance and SSH server port 22?

### ISSUE THREAD

**Issue by DableUTeeF** [anderspitman/SirTunnel#6]
Basically I have no idea what I'm doing. 

From the section `How do you use it?` I still don't really understand where should I run those command.

let's say, I have a webserver running on PC and a Raspberry Pi. 

Can you please kindly elaborate where should I run
 * `run_server.sh`
 * SSH server running on port 22 of example.com
 
And also do I need to have the PATH of `sirtunnel.py` in both Pi and PC?

Many thanks

**Comment by anderspitman** [comment]
Hi @DableUTeeF, sorry this completely slipped through the cracks. If you're not already familiar with creating SSH tunnels by hand, SirTunnel probably isn't the best tool to use.

I'd recommend CloudFlare Tunnel if you want a really simple solution.

Or if you really want to self-host, you can try to find another solution on this list: https://github.com/anderspitman/awesome-tunneling
