### ISSUE TITLE
forward tcp traffic instead of http

### ISSUE THREAD

**Issue by debianmaster** [anderspitman/SirTunnel#9]
Can i forward tcp traffic on my localhost intead of http using SirTunnel?   if so can you guide me what changes need to be done?

**Comment by anderspitman** [comment]
Yeah, in that case you don't even need Caddy/SirTunnel. Just use standard SSH remote port forwarding:

https://goteleport.com/blog/ssh-tunneling-explained/

**Comment by anderspitman** [comment]
Let me know if you have any more questions.
